def Jackofclubs():
    print('					 _________')
    print('					|J /~~|_  |')
    print('					|+ | o`,  |')
    print('					|  | -|   |')
    print('					| =~)+(_= |')
    print('					|   |- |  |')
    print('					|  `.o | +|')
    print('					|  ~|__/ P|')
    print('					 ~~~~~~~~~')
def Jackofspades():
    print('					 _________ ')
    print('					|J /~~|_  |')
    print('					|@ ! -\   |')
    print('					|  \ -!   |')
    print('					|  ^,\^,  |')
    print('					|   I- \  |')
    print('					|   \- I @|')
    print('					|  ~|__/ P|')
    print('					 ~~~~~~~~~ ')
def Jackofdiamonds():
    print('					 _________ ')
    print('					|J /~~|_  |')
    print('					|O ( o\   |')
    print('					|  ! \l   |')
    print('					| ^^^Xvvv |')
    print('					|   l\ I  |')
    print('					|   \o ) O|')
    print('					|  ~|__/ P|')
    print('					 ~~~~~~~~~ ')
def Jackofhearts():
    print('					 _________ ')
    print('					|J /~~|_  |')
    print('					|# % *`.  |')
    print('					|  % <~   |')
    print('					| %% / %% |')
    print('					|   _> %  |')
    print('					|  `,* % #|')
    print('					|  ~|__/ P|')
    print('					 ~~~~~~~~~ ')
def Kingofclubs():
    print('					 _________ ')
    print('					|K |/|\|  |')
    print('					|+ /o,o\  |')
    print('					|  \_-_/  |')
    print('					| ~-_-~-_ |')
    print('					|  /~-~\  |')
    print('					|  \o`o/ +|')
    print('					|  |\|/| X|')
    print('					 ~~~~~~~~~ ')
def Kingofdiamonds():
    print('					 _________ ')
    print('					|K |/|\|  |')
    print('					|O |o.o|  |')
    print('					|   \v/   |')
    print('					|  XXXXX  |')
    print('					|   /^\   |')
    print('					|  |o^o| O|')
    print('					|  |\|/| X|')
    print('					 ~~~~~~~~~ ')
def Kingofhearts():
    print('					 _________ ')
    print('					|K |/|\|  |')
    print('					|# %*,*%  |')
    print('					|  \_o_/  |')
    print('					| #>-=-<# |')
    print('					|  /~o~\  |')
    print('					|  %*^*% #|')
    print('					|  |\|/| X|')
    print('					 ~~~~~~~~~ ')
def Kingofspades():
    print('					 _________ ')
    print('					|K |/|\|  |')
    print('					|@ \- -/  |')
    print('					| ! |-|   |')
    print('					|  % I %  |')
    print('					|   |-| ! |')
    print('					|  /- -\ @|')
    print('					|  |\|/| X|')
    print('					 ~~~~~~~~~ ')
def Queenofclubs():
    print('					 _________ ')
    print('					|Q |~~~|  |')
    print('					|+ /o,o\  |')
    print('					|  \_-_/  |')
    print('					| _-~+_-~ |')
    print('					|  /~-~\  |')
    print('					|  \o`o/ +|')
    print('					|  |___| Q|')
    print('					 ~~~~~~~~~ ')
def Queenofdiamonds():
    print('					 _________ ')
    print('					|Q |~~~|  |')
    print('					|O |o.o|  |')
    print('					|   \v/   |')
    print('					|  XXOXX  |')
    print('					|   /^\   |')
    print('					|  |o^o| O|')
    print('					|  |___| Q|')
    print('					 ~~~~~~~~~ ')
def Queenofhearts():
    print('					 _________ ')
    print('					|Q |~~~|  |')
    print('					|# %*,*%  |')
    print('					|  \_o_/  |')
    print('					| -=<*>=- |')
    print('					|  /~o~\  |')
    print('					|  %*^*% #|')
    print('					|  |___| Q|')
    print('					 ~~~~~~~~~ ')
def Queenofspades():
    print('					 _________ ')
    print('					|Q |~~~|  |')
    print('					|@ \- -/  |')
    print('					| o |-|   |')
    print('					|  I % I  |')
    print('					|   |-| o |')
    print('					|  /- -\ @|')
    print('					|  |___| Q|')
    print('					 ~~~~~~~~~ ')
def Aceofclubs():
    print('					 _________ ')
    print('					|A        |')
    print('					|+   *    |')
    print('					|    !    |')
    print('					|  *-+-*  |')
    print('					|    |    |')
    print('					|   ~~~  +|')
    print('					|        V|')
    print('					 ~~~~~~~~~ ')
def Aceofdiamonds():
    print('					 _________ ')
    print('					|A        |')
    print('					|O  /~\   |')
    print('					|  / ^ \  |')
    print('					| ( <O> ) |')
    print('					|  \ v /  |')
    print('					|   \_/  O|')
    print('					|        V|')
    print('					 ~~~~~~~~~ ')
def Aceofspades():
    print('					 _________ ')
    print('					|A        |')
    print('					|@   *    |')
    print('					|   / \   |')
    print('					|  /_@_\  |')
    print('					|    !    |')
    print('					|   ~ ~  @|')
    print('					|        V|')
    print('					 ~~~~~~~~~ ')
def Aceofhearts():
    print('					 _________ ')
    print('					|A        |')
    print('					|# _   _  |')
    print('					| / ~V~ \ |')
    print('					| \ Bej / |')
    print('					|  \ # /  |')
    print('					|   `.`  #|')
    print('					|        V|')
    print('					 ~~~~~~~~~ ')
def tenofclubs():
    print('					 _________ ')
    print('					|10+   +  |')
    print('					|+   +    |')
    print('					|  +   +  |')
    print('					|         |')
    print('					|  +   +  |')
    print('					|    +   +|')
    print('					|  +   +0l|')
    print('					 ~~~~~~~~~ ')
def tenofdiamonds():
    print('					 _________ ')
    print('					|10O   O  |')
    print('					|O   O    |')
    print('					|  O   O  |')
    print('					|         |')
    print('					|  O   O  |')
    print('					|    O   O|')
    print('					|  O   O0l|')
    print('					 ~~~~~~~~~ ')
def tenofspades():
    print('					 _________ ')
    print('					|10@   @  |')
    print('					|@   @    |')
    print('					|  @   @  |')
    print('					|         |')
    print('					|  @   @  |')
    print('					|    @   @|')
    print('					|  @   @0l|')
    print('					 ~~~~~~~~~ ')
def tenofhearts():
    print('					 _________ ')
    print('					|10#   #  |')
    print('					|#   #    |')
    print('					|  #   #  |')
    print('					|         |')
    print('					|  #   #  |')
    print('					|    #   #|')
    print('					|  #   #0l|')
    print('					 ~~~~~~~~~ ')
def nineofclubs():
    print('					 _________ ')
    print('					|9 +   +  |')
    print('					|+        | ')
    print('					|  +   +  | ')
    print('					|    +    |')
    print('					|  +   +  |')
    print('					|        +|')
    print('					|  +   + 6|  ')
    print('					 ~~~~~~~~~ ')
def nineofdiamonds():
    print('					 _________ ')
    print('					|9 O   O  |')
    print('					|O        |')
    print('					|  O   O  |')
    print('					|    O    |')
    print('					|  O   O  |')
    print('					|        O|')
    print('					|  O   O 6|')
    print('					 ~~~~~~~~~ ')
def nineofspades():
    print('					 _________ ')
    print('					|9 @   @  |')
    print('					|@        |')
    print('					|  @   @  |')
    print('					|    @    |')
    print('					|  @   @  |')
    print('					|        @|')
    print('					|  @   @ 6')
    print('					 ~~~~~~~~~ ')
def nineofhearts():
    print('					 _________ ')
    print('					|9 #   #  |')
    print('					|#        |')
    print('					|  #   #  |')
    print('					|    #    |')
    print('					|  #   #  |')
    print('					|        #|')
    print('					|  #   # 6|')
    print('					 ~~~~~~~~~ ')
def eightofclubs():
    print('					 _________ ')
    print('					|8 +   +  |')
    print('					|+        |')
    print('					|  +   +  |')
    print('					|         |')
    print('					|  +   +  |')
    print('					|        +|')
    print('					|  +   + 8|')
    print('					 ~~~~~~~~~ ')
def eightofdiamonds():
    print('					 _________ ')
    print('					|8 O   O  |')
    print('					|O        |')
    print('					|  O   O  |')
    print('					|         | ')
    print('					|  O   O  |')
    print('					|        O|')
    print('					|  O   O 8|')
    print('					 ~~~~~~~~~ ')
def eightofspades():
    print('					 _________ ')
    print('					|8 @   @  |')
    print('					|@        |')
    print('					|  @   @  |')
    print('					|         |')
    print('					|  @   @  |')
    print('					|        @|')
    print('					|  @   @ 8|')
    print('					 ~~~~~~~~~ ')
def eightofhearts():
    print('					 _________ ')
    print('					|8 #   #  |')
    print('					|#        |')
    print('					|  #   #  |')
    print('					|         |')
    print('					|  #   #  |')
    print('					|        #|')
    print('					|  #   # 8|')
    print('					 ~~~~~~~~~ ')
def sevenofclubs():
    print('					 _________ ')
    print('					|7        | ')
    print('					|+ +   +  |')
    print('					|    +    |')
    print('					|  +   +  |')
    print('					|         |')
    print('					|  +   + +|')
    print('					|        L|')
    print('					 ~~~~~~~~~ ')
def sevenofdiamonds():
    print('					 _________ ')
    print('					|7        |')
    print('					|O O   O  |')
    print('					|    O    |')
    print('					|  O   O  |')
    print('					|         |')
    print('					|  O   O O|')
    print('					|        L|')
    print('					 ~~~~~~~~~ ')
def sevenofspades():
    print('					 _________ ')
    print('					|7        |')
    print('					|@ @   @  |')
    print('					|    @    |')
    print('					|  @   @  |')
    print('					|         |')
    print('					|  @   @ @|')
    print('					|        L|')
    print('					 ~~~~~~~~~ ')
def sevenofhearts():
    print('					 _________ ')
    print('					|7        |')
    print('					|# #   #  |')
    print('					|    #    |')
    print('					|  #   #  |')
    print('					|         |')
    print('					|  #   # #|')
    print('					|        L|')
    print('					 ~~~~~~~~~ ')
def sixofhearts():
    print('					 _________ ')
    print('					|6        |')
    print('					|# #   #  |')
    print('					|         |')
    print('					|  #   #  |')
    print('					|         |')
    print('					|  #   # #|')
    print('					|        9|')
    print('					 ~~~~~~~~~ ')
def sixofclubs():
    print('					 _________ ')
    print('					|6        |')
    print('					|+ +   +  |')
    print('					|         |')
    print('					|  +   +  |')
    print('					|         |')
    print('					|  +   + +|')
    print('					|        9|')
    print('					 ~~~~~~~~~ ')
def sixofdiamonds():
    print('					 _________ ')
    print('					|6        |')
    print('					|O O   O  |')
    print('					|         |')
    print('					|  O   O  |')
    print('					|         |')
    print('					|  O   O O|')
    print('					|        9|')
    print('					 ~~~~~~~~~ ')
def sixofspades():
    print('					 _________ ')
    print('					|6        |')
    print('					|@ @   @  |')
    print('					|         |')
    print('					|  @   @  |')
    print('					|         |')
    print('					|  @   @ @|')
    print('					|        9|')
    print('					 ~~~~~~~~~ ')
def fiveofclubs():
    print('					 _________ ')
    print('					|5        |')
    print('					|+        |')
    print('					|  +   +  |')
    print('					|    +    |')
    print('					|  +   +  |')
    print('					|        +|')
    print('					|        S|')
    print('					 ~~~~~~~~~ ')
def fiveofdiamonds():
    print('					 _________ ')
    print('					|5        |')
    print('					|O        |')
    print('					|  O   O  |')
    print('					|    O    |')
    print('					|  O   O  |')
    print('					|        O|')
    print('					|        S|')
    print('					 ~~~~~~~~~ ')
def fiveofspades():
    print('					 _________ ')
    print('					|5        |')
    print('					|@        |')
    print('					|  @   @  |')
    print('					|    @    |')
    print('					|  @   @  |')
    print('					|        @|')
    print('					|        S|')
    print('					 ~~~~~~~~~ ')
def fiveofhearts():
    print('					 _________ ')
    print('					|5        |')
    print('					|#        |')
    print('					|  #   #  | ')
    print('					|    #    |')
    print('					|  #   #  |')
    print('					|        #|')
    print('					|        S|')
    print('					 ~~~~~~~~~ ')
def fourofclubs():
    print('					 _________ ')
    print('					|4        |')
    print('					|+        |')
    print('					|  +   +  |')
    print('					|         |')
    print('					|  +   +  |')
    print('					|        +|')
    print('					|        b|')
    print('					 ~~~~~~~~~ ')
def fourofdiamonds():
    print('					 _________ ')
    print('					|4        |')
    print('					|O        |')
    print('					|  O   O  | ')
    print('					|         |')
    print('					|  O   O  |')
    print('					|        O|')
    print('					|        b|')
    print('					 ~~~~~~~~~ ')
def fourofhearts():
    print('					 _________ ')
    print('					|4        |')
    print('					|#        |')
    print('					|  #   #  |')
    print('					|         |')
    print('					|  #   #  |')
    print('					|        #|')
    print('					|        b|')
    print('					 ~~~~~~~~~ ')
def fourofspades():
    print('					 _________ ')
    print('					|4        |')
    print('					|@        |')
    print('					|  @   @  |')
    print('					|         |')
    print('					|  @   @  |')
    print('					|        @|')
    print('					|        b|')
    print('					 ~~~~~~~~~ ')
def threeofclubs():
    print('					 _________ ')
    print('					|3        |')
    print('					|+   +    |')
    print('					|         |')
    print('					|    +    |')
    print('					|         |')
    print('					|    +   +|')
    print('					|        E|')
    print('					 ~~~~~~~~~ ')
def threeofdiamonds():
    print('					 _________ ')
    print('					|3        |')
    print('					|O   O    |')
    print('					|         |')
    print('					|    O    |')
    print('					|         |')
    print('					|    O   O|')
    print('					|        E|')
    print('					 ~~~~~~~~~ ')
def threeofspades():
    print('					 _________ ')
    print('					|3        |')
    print('					|@   @    |')
    print('					|         |')
    print('					|    @    |')
    print('					|         |')
    print('					|    @   @|')
    print('					|        E|')
    print('					 ~~~~~~~~~ ')
def threeofhearts():
    print('					 _________ ')
    print('					|3        |')
    print('					|#   #    |')
    print('					|         |')
    print('					|    #    |')
    print('					|         |')
    print('					|    #   #|')
    print('					|        E|')
    print('					 ~~~~~~~~~ ')
def twoofclubs():
    print('					 _________ ')
    print('					|2        |')
    print('					|+        |')
    print('					|    +    |')
    print('					|         |')
    print('					|    +    |')
    print('					|        +|')
    print('					|        Z|')
    print('					 ~~~~~~~~~ ')
def twoofdiamonds():
    print('					 _________ ')
    print('					|2        |')
    print('					|O        |')
    print('					|    O    |')
    print('					|         |')
    print('					|    O    |')
    print('					|        O|')
    print('					|        Z|')
    print('					 ~~~~~~~~~ ')
def twoofspades():
    print('					 _________ ')
    print('					|2        |')
    print('					|@        |')
    print('					|    @    |')
    print('					|         |')
    print('					|    @    |')
    print('					|        @|')
    print('					|        Z|')
    print('					 ~~~~~~~~~ ')
def twoofhearts():
    print('					 _________ ')
    print('					|2        |')
    print('					|#        |')
    print('					|    #    |')
    print('					|         |')
    print('					|    #    |')
    print('					|        #|')
    print('					|        Z|')
    print('					 ~~~~~~~~~ ')
def blankcard():
    print('					 _________ ')
    print('					|*********|')
    print('					|*********|')
    print('					|*********|')
    print('					|*********|')
    print('					|*********|')
    print('					|*********|')
    print('					|*********|')
    print('					 ~~~~~~~~~ ')
